<?php

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function mosaic_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    // Main module help for the metsis_search module.
    /** TODO: Read help from module's README.md */
    case 'help.page.mosaic':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mosaic Tool') . '</p>';
      return $output;

    default:
  }
}


// Implements hook_theme()
function mosaic_theme( $existing, $type, $theme, $path ){
    return [
        'mosaic-template' => [
            'render element' => 'container', // To render a simple container element
            'template' => 'mosaic', // My template file name
            'variables' => [
                'site_name' => "Default",
              ],
        ],
    ];
}



function mosaic_block_info() {
  $blocks = array();
  $blocks['mosaic_block'] = array(
    'info' => t('Mosaic Module'),
  );
  return $blocks;
}

function mosaic_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'mosaic_block':
     $block['content'] = mosaic_main_content(); // set the content of the block to our mosaic_main_content
     break;
  }
  return $block;
}


function mosaic_main_content(){
  global $base_url;
  global $metsis_conf;

  $site_name = variable_get('site_name', 'Default');
  $scr_name = $base_url ."/mosaic";
  $mpath = drupal_get_path('module', 'mosaic');

// define first array with dummy values for "date, id, address, latlong"
  $day = (new DateTime())->modify('-7 day')->format('Y-m-d\TH:i:s\Z'); //today
  //drupal_set_message(print_r($day,TRUE),'warning');
  //drupal_set_message(print_r($day,TRUE),'warning');

// Make 4 different queries depending on AREA which they will be shown switching between tabs
// Q1 tllong(minx): -3.22; brlong(maxx): 55.29;  tllat(maxy): 83.21; brlat(miny): 72.70

  $prinfoQ1 = [];
  $prinfoQ2 = [];
  $prinfoQ3 = [];
  $queryQ1_res = [];
  $queryQ2_res = [];
  $queryQ3_res = [];

  // Define queries and extract prinfo
  $envQ1 = [-2.22, 52.29, 82.21, 72.70];
  $envQ2 = [5.00, 39.25, 70.84, 65.55];
  $envQ3 = [-1.70, 20.42, 66.74, 56.42];
  $envelops = array($envQ1, $envQ2, $envQ3);

  $queryQ1_prd = 'mmd_temporal_extent_start_date:['.$day.' TO *] AND bbox:"Intersects(ENVELOPE(-2.22, 52.29, 82.21, 72.70))"';
  $queryQ2_prd = 'mmd_temporal_extent_start_date:['.$day.' TO *] AND bbox:"Intersects(ENVELOPE(5.00, 39.25, 70.84, 65.55))"';
  $queryQ3_prd = 'mmd_temporal_extent_start_date:['.$day.' TO *] AND bbox:"Intersects(ENVELOPE(-1.70, 20.42, 66.74, 56.42))"';
  $fields = "id, mmd_data_access_resource, mmd_temporal_extent_start_date, mmd_temporal_extent_end_date, mmd_geographic_extent_rectangle_north, mmd_geographic_extent_rectangle_south, mmd_geographic_extent_rectangle_east, mmd_geographic_extent_rectangle_west, mmd_data_access_wms_layers_wms_layer";

  // Define connection to SolR and results of the query
  $con1 = new HttpConnection(SOLR_SERVER_IP, SOLR_SERVER_PORT);
  $con2 = new HttpConnection(SOLR_SERVER_IP, SOLR_SERVER_PORT);
  $con3 = new HttpConnection(SOLR_SERVER_IP, SOLR_SERVER_PORT);
  $resQ1 = $con1->get('/solr/nbs-l1/select', array("q" =>$queryQ1_prd, "start" => 0, "rows" => 1500, "wt" => "json", "fl" => $fields,));
  $resQ2 = $con2->get('/solr/nbs-l1/select', array("q" =>$queryQ2_prd, "start" => 0, "rows" => 1500, "wt" => "json", "fl" => $fields,));
  $resQ3 = $con3->get('/solr/nbs-l1/select', array("q" =>$queryQ3_prd, "start" => 0, "rows" => 1500, "wt" => "json", "fl" => $fields,));
  $queryQ1_res = json_decode($resQ1['body'], true);
  $queryQ2_res = json_decode($resQ2['body'], true);
  $queryQ3_res = json_decode($resQ3['body'], true);


  $count = 0;
  $count2 = 0;
  $count3 = 0;
  foreach ($queryQ1_res['response']['docs'] as $doc) {
     $id = $doc['id'];
     $address = $doc['mmd_data_access_resource'][1];
     $address = json_decode("{".$address."}",true)['OGC WMS'];
     $start = $doc['mmd_temporal_extent_start_date'];
     $end = $doc['mmd_temporal_extent_end_date'];
     $north = $doc['mmd_geographic_extent_rectangle_north'];
     $south = $doc['mmd_geographic_extent_rectangle_south'];
     $east = $doc['mmd_geographic_extent_rectangle_east'];
     $west = $doc['mmd_geographic_extent_rectangle_west'];
     $layers = $doc['mmd_data_access_wms_layers_wms_layer'];
     $latlon = array(($south+$north)/2, ($east+$west)/2);
     $prinfoQ1[$count] = array($address, $id, $layers, array($north,$south,$east,$west), array($start, $end));
     $count = $count + 1;
  }
  foreach ($queryQ2_res['response']['docs'] as $doc) {
     $id = $doc['id'];
     $address = $doc['mmd_data_access_resource'][1];
     $address = json_decode("{".$address."}",true)['OGC WMS'];
     $start = $doc['mmd_temporal_extent_start_date'];
     $end = $doc['mmd_temporal_extent_end_date'];
     $north = $doc['mmd_geographic_extent_rectangle_north'];
     $south = $doc['mmd_geographic_extent_rectangle_south'];
     $east = $doc['mmd_geographic_extent_rectangle_east'];
     $west = $doc['mmd_geographic_extent_rectangle_west'];
     $layers = $doc['mmd_data_access_wms_layers_wms_layer'];
     $latlon = array(($south+$north)/2, ($east+$west)/2);
     $prinfoQ2[$count2] = array($address, $id, $layers, array($north,$south,$east,$west), array($start, $end));
     $count2 = $count2 + 1;
  }
  foreach ($queryQ3_res['response']['docs'] as $doc) {
     $id = $doc['id'];
     $address = $doc['mmd_data_access_resource'][1];
     $address = json_decode("{".$address."}",true)['OGC WMS'];
     $start = $doc['mmd_temporal_extent_start_date'];
     $end = $doc['mmd_temporal_extent_end_date'];
     $north = $doc['mmd_geographic_extent_rectangle_north'];
     $south = $doc['mmd_geographic_extent_rectangle_south'];
     $east = $doc['mmd_geographic_extent_rectangle_east'];
     $west = $doc['mmd_geographic_extent_rectangle_west'];
     $layers = $doc['mmd_data_access_wms_layers_wms_layer'];
     $latlon = array(($south+$north)/2, ($east+$west)/2);
     $prinfoQ3[$count3] = array($address, $id, $layers, array($north,$south,$east,$west), array($start, $end));
     $count3 = $count3 + 1;
  }

  drupal_json_encode($prinfoQ1);
  drupal_add_js(array('prinfoQ1' => $prinfoQ1,
                      'prinfoQ2' => $prinfoQ2,
                      'prinfoQ3' => $prinfoQ3,
                      'envelops' => $envelops
                      ), 'setting');


return '

<!doctype html>
<html lang="en">
  <head>
    <script src="/'.drupal_get_path('module','jquery_update').'/replace/jquery/1.10/jquery.min.js"></script>

    <link rel="stylesheet" href="/'.libraries_get_path('openlayers3').'/css/ol.css" type="text/css">
    <link rel="stylesheet" href="/'.libraries_get_path('openlayers3').'/apidoc/styles/bootstrap.min.css">
    <link rel="stylesheet" href="/'.libraries_get_path('ol3-layerswitcher').'/src/ol3-layerswitcher.css">
    <script src="/'.libraries_get_path('openlayers3').'/build/ol.js" type="text/javascript"></script>
    <script src="/'.libraries_get_path('openlayers3').'/apidoc/scripts/bootstrap.min.js"></script>
    <script src="/'.libraries_get_path('ol3-layerswitcher').'/src/ol3-layerswitcher.js"></script>
    <link rel="stylesheet" href="/'.$mpath.'/css/ol-ext.min.css" />
    <script type="text/javascript" src="/'.$mpath.'/js/ol-ext.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.2.1/proj4.js"></script>
  </head>
  <body>

    <ul class="tabs primary" id="tab-regions">
       <li class="active" id="Q1-tab" onclick="Q1()"><a >Svalbard</a></li>
       <li id="Q2-tab" onclick="Q2()"><a >Northern Norway</a></li>
       <li id="Q3-tab" onclick="Q3()"><a >Southern Norway</a></li>
    </ul>
    <script type="text/javascript">
    if (("'.$site_name.'").includes("sios")) {
       document.getElementById("tab-regions").style.display="none";
    }
    </script>
    <div id="map" class="map">
       <div id="tooltip" style="background-color: rgba(0,0,0,0.2); font-size: small; width:100%;"></div>
       <script type="text/javascript" src="/'.$mpath.'/js/mosaic.js"></script>
    <div class="progress-container">
      <div id="progress"></div>
    </div>
    </div>
      <br>
      <table style="font-size: large; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);">
      <tr><td style="border: unset; background-color: unset; text-align: center; padding: 0.4em"><label>Acquisition Starts: </label><span class="dateStart"></span></td></tr>
      <tr><td style="border: unset; background-color: unset; text-align: center; padding: 0.4em"><label>Acquisition Ends:  </label><span class="dateEnd"></span></td></tr></table>
    <br>

  </body>
</html>
';
}
?>
