<?php

function mosaic_init(){
  $mpath = drupal_get_path('module', 'mosaic');
  drupal_add_js($mpath . '/js/mosaic.js');
  drupal_add_css($mpath . '/css/style_selection.css');
}


function mosaic_block_info() {
  $blocks = array();
  $blocks['mosaic_block'] = array(
    'info' => t('Mosaic Module'),
  );
  return $blocks;
}

function mosaic_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'mosaic_block':
     $block['content'] = mosaic_main_content(); // set the content of the block to our mosaic_main_content
     break;
  }
  return $block;
}


function mosaic_main_content(){
  global $base_url;
  global $metsis_conf;
  
  $site_name = variable_get('site_name', 'Default');
  $scr_name = $base_url ."/mosaic";

// define first array with dummy values for "date, id, address, latlong" 
  $day = (new DateTime())->modify('-4 day')->format('Y-m-d\TH:i:s\Z'); //today
  //drupal_set_message(print_r($today,TRUE),'warning');
  //drupal_set_message(print_r($day,TRUE),'warning');

// Make 4 different queries depending on AREA which they will be shown switching between tabs 
// Q1 tllong: -3.22;   tllat: 83.21; brlong: 55.29; brlat: 72.70
// $query_prd = 'full_text:S*'.$day.'* AND bbox:"Intersects(ENVELOPE(-3.22, 55.29, 83.21, 72.70))"';
// Q2 tllong: 1.92; tllat 74.84; brlong: 39.25; brlat: 65.55  
// $query_prd = 'full_text:S*'.$day.'* AND bbox:"Intersects(ENVELOPE(1.92, 39.25, 74.84, 65.55))"';
// Q3 tllong:-1.70; tllat 66.74; brlong: 20.42; brlat: 56.42  
// $query_prd = 'full_text:S*'.$day.'* AND bbox:"Intersects(ENVELOPE(-1.70, 20.42, 66.74, 56.42))"';

  $prinfoQ1 = [];
  $prinfoQ2 = [];
  $prinfoQ3 = [];
  $queryQ1_res = [];
  $queryQ2_res = [];
  $queryQ3_res = [];

  // Define queries and extract prinfo
  $queryQ1_prd = 'mmd_temporal_extent_start_date:['.$day.' TO *]  AND bbox:"Intersects(ENVELOPE(-2.22, 52.29, 82.21, 72.70))"';
  //$queryQ2_prd = ':S*'.$day.'* AND bbox:"Intersects(ENVELOPE(1.92, 39.25, 74.84, 65.55))"';
  $queryQ2_prd = 'mmd_temporal_extent_start_date:['.$day.' TO *] AND bbox:"Intersects(ENVELOPE(5.00, 39.25, 70.84, 65.55))"';
  //$queryQ3_prd = ':S*'.$day.'* AND bbox:"Intersects(ENVELOPE(-1.70, 20.42, 66.74, 56.42))"';
  $queryQ3_prd = 'mmd_temporal_extent_start_date:['.$day.' TO *] AND bbox:"Intersects(ENVELOPE(-1.70, 20.42, 66.74, 56.42))"';
  $fields = "id, mmd_data_access_resource, mmd_temporal_extent_start_date, mmd_temporal_extent_end_date, mmd_geographic_extent_rectangle_north, mmd_geographic_extent_rectangle_south, mmd_geographic_extent_rectangle_east, mmd_geographic_extent_rectangle_west, mmd_data_access_wms_layers_wms_layer";
   
  // Define connection to SolR and results of the query
  $con1 = new HttpConnection(SOLR_SERVER_IP, SOLR_SERVER_PORT);
  $con2 = new HttpConnection(SOLR_SERVER_IP, SOLR_SERVER_PORT);
  $con3 = new HttpConnection(SOLR_SERVER_IP, SOLR_SERVER_PORT);
  $resQ1 = $con1->get('/solr/nbs-l1/select', array("q" =>$queryQ1_prd, "start" => 0, "rows" => 1000, "wt" => "json", "fl" => $fields,));
  $resQ2 = $con2->get('/solr/nbs-l1/select', array("q" =>$queryQ2_prd, "start" => 0, "rows" => 1000, "wt" => "json", "fl" => $fields,));
  $resQ3 = $con3->get('/solr/nbs-l1/select', array("q" =>$queryQ3_prd, "start" => 0, "rows" => 1000, "wt" => "json", "fl" => $fields,));
  $queryQ1_res = json_decode($resQ1['body'], true);
  $queryQ2_res = json_decode($resQ2['body'], true);
  $queryQ3_res = json_decode($resQ3['body'], true);


  $count = 0; 
  $count2 = 0; 
  $count3 = 0; 
  foreach ($queryQ1_res['response']['docs'] as $doc) {
     $id = $doc['id'];
     $address = $doc['mmd_data_access_resource'][1];
     $address = json_decode("{".$address."}",true)['OGC WMS'];
     $start = $doc['mmd_temporal_extent_start_date'];
     $end = $doc['mmd_temporal_extent_end_date'];
     $north = $doc['mmd_geographic_extent_rectangle_north'];
     $south = $doc['mmd_geographic_extent_rectangle_south'];
     $east = $doc['mmd_geographic_extent_rectangle_east'];
     $west = $doc['mmd_geographic_extent_rectangle_west'];
     $layers = $doc['mmd_data_access_wms_layers_wms_layer'];
     $latlon = array(($south+$north)/2, ($east+$west)/2);
     $prinfoQ1[$count] = array($address, $id, $layers, array($north,$south,$east,$west), array($start, $end));
     $count = $count + 1; 
  }
  foreach ($queryQ2_res['response']['docs'] as $doc) {
     $id = $doc['id'];
     $address = $doc['mmd_data_access_resource'][1];
     $address = json_decode("{".$address."}",true)['OGC WMS'];
     $start = $doc['mmd_temporal_extent_start_date'];
     $end = $doc['mmd_temporal_extent_end_date'];
     $north = $doc['mmd_geographic_extent_rectangle_north'];
     $south = $doc['mmd_geographic_extent_rectangle_south'];
     $east = $doc['mmd_geographic_extent_rectangle_east'];
     $west = $doc['mmd_geographic_extent_rectangle_west'];
     $layers = $doc['mmd_data_access_wms_layers_wms_layer'];
     $latlon = array(($south+$north)/2, ($east+$west)/2);
     $prinfoQ2[$count2] = array($address, $id, $layers, array($north,$south,$east,$west), array($start, $end));
     $count2 = $count2 + 1; 
  }
  foreach ($queryQ3_res['response']['docs'] as $doc) {
     $id = $doc['id'];
     $address = $doc['mmd_data_access_resource'][1];
     $address = json_decode("{".$address."}",true)['OGC WMS'];
     $start = $doc['mmd_temporal_extent_start_date'];
     $end = $doc['mmd_temporal_extent_end_date'];
     $north = $doc['mmd_geographic_extent_rectangle_north'];
     $south = $doc['mmd_geographic_extent_rectangle_south'];
     $east = $doc['mmd_geographic_extent_rectangle_east'];
     $west = $doc['mmd_geographic_extent_rectangle_west'];
     $layers = $doc['mmd_data_access_wms_layers_wms_layer'];
     $latlon = array(($south+$north)/2, ($east+$west)/2);
     $prinfoQ3[$count3] = array($address, $id, $layers, array($north,$south,$east,$west), array($start, $end));
     $count3 = $count3 + 1; 
  }

  //drupal_set_message(print_r($prinfoQ1,TRUE),'warning');
  drupal_json_encode($prinfoQ1);
  drupal_add_js(array('prinfoQ1' => $prinfoQ1, 
                      'prinfoQ2' => $prinfoQ2, 
                      'prinfoQ3' => $prinfoQ3
                      ), 'setting');
  

return $out . '

<!doctype html>                                                                                                                                                                                                         
<html lang="en">                                                                                                                                                                                                        
  <head>                                                                                                                                          
    <script src="/sites/all/modules/jquery_update/replace/jquery/1.10/jquery.min.js"></script>

    <link rel="stylesheet" href="/sites/'.$site_name.'/libraries/openlayers3/css/ol.css" type="text/css">
    <link rel="stylesheet" href="/sites/'.$site_name.'/libraries/openlayers3/apidoc/styles/bootstrap.min.css">
    <link rel="stylesheet" href="/sites/'.$site_name.'/libraries/ol3-layerswitcher/src/ol3-layerswitcher.css">
    <script src="/sites/'.$site_name.'/libraries/openlayers3/build/ol.js" type="text/javascript"></script>
    <script src="/sites/'.$site_name.'/libraries/openlayers3/apidoc/scripts/bootstrap.min.js"></script>
    <script src="/sites/'.$site_name.'/libraries/ol3-layerswitcher/src/ol3-layerswitcher.js"></script>
    <link rel="stylesheet" href="https://cdn.rawgit.com/Viglino/ol-ext/master/dist/ol-ext.min.css" />
    <script type="text/javascript" src="https://cdn.rawgit.com/Viglino/ol-ext/master/dist/ol-ext.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.2.1/proj4.js"></script>
    <style>
      #info {
        height: 1px;
        width: 1px;
        z-index: 100;
        /*left: 200px;
        top: 100px;*/
      }
      .popover {
        max-width: unset;
        left: 100px;
        top: 100px;
      }
      .popover table tr td {
        padding: 0 2px 0 2px;
      }
      .popover.top {
      }
      .ol-mouse-position {
         top: 5%;
         left: 5%;
      }
      .ol-overlay-container {
        position: unset !important;
      }
      #tooltip {
         font-weight: bold;
         padding: 5px;
      }
      .progress-container {
        width:100%;
        height: 10px;
        background-color: #dcdcdc;
      }
      #progress {
        position: relative;
        height: 10px;
        background: -webkit-linear-gradient(left, #dcdcdc 0%, #7593b9 100%);
        width: 0%;
        max-width: 100%;
        transition: width 250ms;
      }
      
    </style>
  </head>
  <body>

    <div id="tooltip" style="background-color: rgba(0,0,0,0.2); font-size: small"></div>
    <ul class="tabs primary">
       <li class="active" id="Q1-tab" onclick="Q1()"><a >Svalbard</a></li>
       <li id="Q2-tab" onclick="Q2()"><a >Northern Norway</a></li>
       <li id="Q3-tab" onclick="Q3()"><a >Southern Norway</a></li>
    </ul>
    <div id="map" class="map">
       <script type="text/javascript" src="/sites/'.$site_name.'/modules/mosaic/js/mosaic.js"></script>
    <div class="progress-container">
      <div id="progress"></div>
    </div>
    </div>
      <br>
      <table style="font-size: large; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);"> 
      <tr><td style="border: unset; background-color: unset; text-align: center; padding: 0.4em"><label>Acquisition Starts: </label><span class="dateStart"></span></td></tr>
      <tr><td style="border: unset; background-color: unset; text-align: center; padding: 0.4em"><label>Acquisition Ends:  </label><span class="dateEnd">End: </span></td></tr></table>
    <br>


  </body>
</html>
';
}
?>
